### ISSUE TITLE
Why did you insert [CLS] token at the last? Should't it be first?

### ISSUE THREAD

**Issue by Boltzmachine** [athms/learning-from-brains#3]
from the code, it seems that you append the [CLS] to the last of the sequence, shouldn't it be at the first position?

https://github.com/athms/learning-from-brains/blob/b061ef97680365a074671e0c95581af426773f9e/src/embedder/csm.py#L157-L166

**Comment by athms** [comment]
thanks for the question! the [cls] token needs to be at the end of the sequence due to the causal attention mechanism of the transformer decoder model, which we are training in the CSM task.

**Comment by Boltzmachine** [comment]
> thanks for the question! the [cls] token needs to be at the end of the sequence due to the causal attention mechanism of the transformer decoder model, which we are training in the CSM task.

Thanks for your quick reply! 
However, in your `BertEmbedder`, you still use this function, which means you still append the [CLS] at the last. Do you think I should modify this function to insert [CLS] to the first for a BERT model?

**Comment by athms** [comment]
Yes, that is correct. Thanks for bringing this to my attention! I will write/push a fix in the next few days. thanks!
